### ISSUE TITLE
Create NotificationService

### ISSUE THREAD

**Issue by mduu** [mduu/tauchbolde#1]
NotificationService need to collect notification entrys per user and sends them all together depending on the configured interval by email to each user. The notification serverice needs to be smart about who gets which notifications:

- Don't notify the author / source of a notification
- Don't notify users who are not interested in a particular event
- ...

## ToDo:
- [x] Implement base system
- [x] Implement tests for NotificationSender
- [x] Implement tests for Formatter
