### ISSUE TITLE
Improve mobile layout

### ISSUE THREAD

**Issue by mduu** [mduu/tauchbolde#22]
The general responsivness for small screen (smart-phones) is already quite good. Neverless there are some places where we can optimise things.

**Tasks:**

- [x] List of events is a wide and not responsive
- [x] Profile cards has non-optimal text breaks
- [x] Event details header has non-optimal text breaks
