### ISSUE TITLE
Logbuch

### ISSUE THREAD

**Issue by mduu** [mduu/tauchbolde#3]
Unterstützung für Logbuch-Einträge (aka "News" bzw. "Vergangenes"). Logbucheinträge bestehen aus einem Titel, einem Text (inkl. Markdown Formatierung), Autor, Erstellungsdatum, Modifkationsdatum, Teaser-Image und Teaser-Thumbnail.

Das Logbuch sollen auf einer eigenen Seite angeschaut und von berechtigten Personen (= Mitglieder) erstellt und verwaltet werden können. Zudem sollen die neusten Logbucheinträge auch auf der Frontseite eingeblendet werden. Der Link "Mehr ..." soll auf die Logbuch-Seite führen.

Angezeigt sollen auch Autor-Informationen inkl. dem Avatar des Autors sowie Erstellungszeit und falls vorhanden die Modifikationszeit. Der Logbuch-Text soll Textformatierungen unterstützen (Markdown). Hierzu sollen die bestehenden Helpers verwendet werden.

**Tasks:**

- [x] Entitäten
- [x] Datenbank-Schema / Migrationsscripts
- [x] Logbuch-Seite
- [x] Logbucheinträge als Liste anzeigen
- [x] Erfassen und bearbeiten von Logbucheinträgen
- [x] Anzeigen von Lochbucheinträgen (Detailansicht)
- [x] Logbuch-Widget auf Startseite und ggf. in "Über uns"
- [x] Publizieren von Logbucheinträgen
- [x] Menueintrag erstellen
- [x] Emailbenachrichtung via best. Notification-System bei neuen Logbucheinträgen
- [x] AzureBlob anbinden
