### ISSUE TITLE
Kommentarfunktion für Logbuch von Tauchbolden

### ISSUE THREAD

**Issue by mduu** [mduu/tauchbolde#59]
Angemeldete Tauchbolde sollen Kommentare zu Logbucheinträgen hinterlegen können. Diese Kommentare können autom. veröffentlicht werden da es sich um authentifizierte Tauchbolde handelt.

**Tasks:**

- [ ] Entity model und Migrations
- [ ] Kommentare erfassen (UI und Backend)
- [ ] Kommentare löschen und bearbeiten (UI und Backend)
- [ ] Email Benachrichtigung

Informationen zum Logbuch siehe #3.
